# Generated by Django 4.0 on 2021-12-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videodata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tite', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='thumbnails')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videodata.videodatamodel')),
            ],
        ),
    ]
