# Generated by Django 4.0 on 2021-12-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videodata', '0003_videodatamodel_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='video_id',
            new_name='video',
        ),
    ]
