# Generated by Django 4.0 on 2021-12-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videodata', '0004_rename_video_id_thumbnail_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbnail',
            new_name='ThumbnailModel',
        ),
    ]
