# Generated by Django 4.0 on 2021-12-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videodata', '0005_rename_thumbnail_thumbnailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnailmodel',
            old_name='tite',
            new_name='title',
        ),
    ]
