# Generated by Django 4.0 on 2021-12-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videodata', '0006_rename_tite_thumbnailmodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnailmodel',
            old_name='title',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='thumbnailmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='videodata.videodatamodel'),
        ),
    ]
